### ISSUE TITLE
received signal SIGSEGV, Segmentation fault

### ISSUE THREAD

**Issue by Mephostopilis** [DanielChappuis/reactphysics3d#174]
```
#0  0x00007ffff20a1219 in reactphysics3d::HeapAllocator::release (this=0x7ffff232ec30 <physicsCommon+16>, pointer=0x7ffff1a9d6ff, size=<optimized out>)
    at lualib-src/reactphysics3d/src/memory/HeapAllocator.cpp:202
#1  0x00007ffff20a0c1a in reactphysics3d::SingleFrameAllocator::release (this=0x7ffff232f0d8 <physicsCommon+1208>, pointer=<optimized out>, size=<optimized out>)
    at lualib-src/reactphysics3d/src/memory/SingleFrameAllocator.cpp:90
#2  0x00007ffff20543e7 in reactphysics3d::List<reactphysics3d::ContactManifoldInfo>::reserve (capacity=32, this=0x7ffff19da555)
    at lualib-src/reactphysics3d/include/reactphysics3d/containers/List.h:274
#3  reactphysics3d::List<reactphysics3d::ContactManifoldInfo>::add (element=..., this=0x7ffff19da555)
    at lualib-src/reactphysics3d/include/reactphysics3d/containers/List.h:288
#4  reactphysics3d::CollisionDetectionSystem::processPotentialContacts (this=0x7ffff19d97cd, this@entry=0x7ffff19d0001, narrowPhaseInfoBatch=...,
    updateLastFrameInfo=true, updateLastFrameInfo@entry=100, potentialContactPoints=..., mapPairIdToContactPairIndex=0x7ffff19da615, potentialContactManifolds=...,
    contactPairs=0x7ffff19da595, mapBodyToContactPairs=...) at lualib-src/reactphysics3d/src/systems/CollisionDetectionSystem.cpp:1128
#5  0x00007ffff2054c87 in reactphysics3d::CollisionDetectionSystem::processAllPotentialContacts (this=0x7ffff19d0001, this@entry=0x7ffff19d97cd, narrowPhaseInput=...,
    updateLastFrameInfo=100, updateLastFrameInfo@entry=true, potentialContactPoints=..., mapPairIdToContactPairIndex=<optimized out>, potentialContactManifolds=...,
    contactPairs=<optimized out>, mapBodyToContactPairs=...) at lualib-src/reactphysics3d/src/systems/CollisionDetectionSystem.cpp:509
#6  0x00007ffff2054d3f in reactphysics3d::CollisionDetectionSystem::computeNarrowPhase (this=this@entry=0x7ffff19d97cd)
    at lualib-src/reactphysics3d/src/systems/CollisionDetectionSystem.cpp:527
#7  0x00007ffff2054de6 in reactphysics3d::CollisionDetectionSystem::computeCollisionDetection (this=this@entry=0x7ffff19d97cd)
    at lualib-src/reactphysics3d/src/systems/CollisionDetectionSystem.cpp:95
#8  0x00007ffff207c65b in reactphysics3d::PhysicsWorld::update (this=0x7ffff19d8da5, timeStep=0.0166666675)
```

**Comment by DanielChappuis** [comment]
Thanks for reporting this.

Do you have some code so that I can reproduce this issue ?
